wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1734301995
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.9.16
      5: 0.17.4
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 3.22351364612602e-05
seed:
  desc: null
  value: 42
